export const input = {
  title: 'BSON Date',
  bsonType: 'object',
  properties: {
    date: {
      bsonType: 'date'
    }
  },
  required: ['date'],
  additionalProperties: false
}

export const output = `/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface BSONDate {
  date: Date;
}
`
